# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title bubble sort algorithm using Rcpp
#' @description bubble sort algorithm using Rcpp
#' @param arr Array to be sorted
#' @return the sorted array
#' @examples
#' \dontrun{
#' dt <- c(1,4,6,3,2);
#' bubbleSortCpp(dt);
#' }
#' @export
bubbleSortCpp <- function(arr) {
    .Call('_StatComp22092_bubbleSortCpp', PACKAGE = 'StatComp22092', arr)
}

